2024-03-18 18:35:52,745 - ERROR - Произошла ошибка: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016492589100>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера'))
2024-03-18 20:54:06,612 - ERROR - Не удалось получить IAM токен.
2024-03-18 20:56:13,534 - ERROR - Не удалось получить IAM токен.
2024-03-18 20:58:10,993 - ERROR - Не удалось получить IAM токен.
2024-03-18 21:19:37,645 - ERROR - Не удалось получить IAM токен.
2024-03-18 21:22:07,981 - ERROR - Не удалось получить IAM токен.
2024-03-19 12:30:12,762 - ERROR - Не удалось получить IAM токен.
2024-03-19 12:30:42,358 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-03-19 12:30:42,358 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\evsee\PycharmProjects\pussy\.venv\lib\site-packages\telebot\__init__.py", line 1140, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\evsee\PycharmProjects\pussy\.venv\lib\site-packages\telebot\util.py", line 110, in raise_exceptions
    raise self.exception_info
  File "C:\Users\evsee\PycharmProjects\pussy\.venv\lib\site-packages\telebot\util.py", line 92, in run
    task(*args, **kwargs)
  File "C:\Users\evsee\PycharmProjects\pussy\.venv\lib\site-packages\telebot\__init__.py", line 661, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\evsee\PycharmProjects\pussy\.venv\lib\site-packages\telebot\__init__.py", line 633, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\evsee\PycharmProjects\pussy\.venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\evsee\PycharmProjects\pussy\.venv\lib\site-packages\telebot\apihelper.py", line 164, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\evsee\PycharmProjects\pussy\.venv\lib\site-packages\telebot\apihelper.py", line 191, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-03-19 21:34:12,283 - ERROR - Не удалось получить IAM токен.
2024-03-19 21:43:51,093 - ERROR - Не удалось получить IAM токен.
2024-03-19 21:52:24,069 - ERROR - Не удалось получить IAM токен.
